#!/usr/bin/env bash

git_root="$(git rev-parse --show-toplevel)"
PYTHON_VERSION=$(cat ${git_root}/.python-version)

if ! command -v pip >/dev/null 2>&1; then
    echo "pip not installed. Install it and try again."
    exit 1
fi
pip install -r requirements.txt

if ! command -v pyenv >/dev/null 2>&1; then
    echo "pyenv not installed. Install it and try again."
    exit 1
fi
pyenv version | grep -q ${PYTHON_VERSION} || pyenv install ${PYTHON_VERSION}
